### ISSUE TITLE
program always ask for authenticator codes

### ISSUE THREAD

**Issue by afraga-br** [LavishSoftware/ISBoxerEVELauncher#13]
I have to put auth codes on every account every time I log with them. It would be nice if it behaves like the official eve launcher: I only would have to put the auth code once and after that the program would launch all accounts without asking for the auth code.

**Comment by JamesDenholm** [comment]
Yeah, asking for auth codes on every launch -- especially when you're looking at multiple accounts -- is just gonna drive people to turn 2FA off entirely.

**Comment by smbonn2005** [comment]
Having the same problem here, and does it every time. Just launching a handful of accounts and it becomes a pain quickly.

**Comment by afraga-br** [comment]
Hi guys, any plans for this improvement? It's really annoying to login in the current state...

**Comment by LaxLacks** [comment]
Fixed as of 1.0.0.18
