### ISSUE TITLE
empty chat channels ingame when lauched as Character

### ISSUE THREAD

**Issue by likta** [LavishSoftware/ISBoxerEVELauncher#15]
When EVE is lauched as "EVE Accounts" (with or without Inner Space, does not matter) all ingame channels work perfect.
When EVE is launched as "EVE Characters" (with or without Inner Space, does not matter) all ingame channels are empty as shown below.

Character names do not contain special signs.
![image](https://user-images.githubusercontent.com/33384899/32411331-42dbddd0-c1d8-11e7-9e01-c5597f0606d7.png)

**Comment by smbonn2005** [comment]
Having this same problem as well

**Comment by Boot103** [comment]
I also get this problem.

**Comment by Wildgear** [comment]
same

**Comment by pyataku** [comment]
same here

**Comment by Moremackles** [comment]
Same here although it's only my local channel that behaves like this, note that jumping to other systems or attempting to open local through the channel browser also doesn't work

**Comment by Loldag** [comment]
I have the same problem any quick fix or update being worked on?

**Comment by Moremackles** [comment]
You can solve the issue by not using character launching but instead using account launching, that seemed to fix it for me.

**Comment by trek-e** [comment]
I launch one account as a character and others where I pick and I'm not seeing this issue anymore.   After the chat channels refresh / change to xmpp did this go away?

**Comment by LaxLacks** [comment]
This specific issue may be fixed, but other random issues have been reported when using Character login.

A warning was added to ISBEL that EVE has random issues when using Character login. It is my understanding that these are low priority EVE bugs, as the option to log in directly to a Character is not generally available.
