### ISSUE TITLE
Expand button for routing not work when lauched as Character

### ISSUE THREAD

**Issue by Terpla** [LavishSoftware/ISBoxerEVELauncher#21]
When eve is launched as "EVE Characters" (without Inner Space) all buttons don't expanded.
![image](https://i.imgur.com/Ud04skz.png)
command line parametes:
`"E:\Games\Eve\Client\SharedCache\tq\bin\exefile.exe" /noconsole /ssoToken=123 /character=123`
but if i launch as "EVE Accounts" (without Inner Space) all buttons works perfect:
![image](https://i.imgur.com/hKBwUDo.png)
command line parametes:
`"E:\Games\Eve\Client\SharedCache\tq\bin\exefile.exe" /noconsole /ssoToken=123`
This bug reproduced also when i launch as "EVE Accounts" (without Inner Space) with "/triPlatform=dx11" parameter.

**Comment by LaxLacks** [comment]
A warning was added to ISBEL that EVE has random issues when using Character login. It is my understanding that these are low priority EVE bugs, as the option to log in directly to a Character is not generally available.
