### ISSUE TITLE
Account.cs wrong Redirect URI no login success

### ISSUE THREAD

**Issue by BluePeer** [LavishSoftware/ISBoxerEVELauncher#23]
at 852
string uri = "https://login.eveonline.com/account/verifytwofactor?ReturnUrl=%2Foauth%2Fauthorize%2F%3Fclient_id%3DeveLauncherTQ%26lang%3Den%26response_type%3Dtoken%26redirect_uri%3D---- >>>>>>>> https%3A%2F%2Fsisilogin.testeveonline.com%2Flauncher%3Fclient_id%3DeveLauncherTQ

%26scope%3DeveClientToken";
            if (sisi)
            {
                uri = "https://sisilogin.testeveonline.com/account/verifytwofactor?ReturnUrl=%2Foauth%2Fauthorize%2F%3Fclient_id%3DeveLauncherTQ%26lang%3Den%26response_type%3Dtoken%26redirect_uri%3Dhttps%3A%2F%2Fsisilogin.testeveonline.com%2Flauncher%3Fclient_id%3DeveLauncherTQ%26scope%3DeveClientToken";
            }

**Comment by wanjizheng** [comment]
I've got the same issue.

{"error":"invalid_request","error_description":"The callback URI doesn't match the value stored for this client"}

**Comment by wanjizheng** [comment]
Moreover, the VerificationCodeChallengeWindow.xaml file is missing from the source code.

**Comment by LaxLacks** [comment]
Resolved in latest commits and 1.0.0.25. Thanks :)
