### ISSUE TITLE
Invalid EVE Character

### ISSUE THREAD

**Issue by wanjizheng** [LavishSoftware/ISBoxerEVELauncher#31]
In the latest release 1.0.0.28, the "Add Character" function doesn't work properly with the following error message:
Invalid EVE Character -- Failed to find Character ID via ESI.

**Comment by gritche70** [comment]
Confirm, i pass from 26 to 28 and had to delete the settings.XML, and so to reconfigure every account, that's impossible du to the Invalid EVE Character -- Failed to find Character ID via ESI bug

**Comment by xSINIQx** [comment]
same here. trying to add my characters on my new setup and i also get "Failed to find Character ID via ESI."
