### ISSUE TITLE
Add automatic character selection by specifying /character=charid

### ISSUE THREAD

**Issue by Nothing4You** [LavishSoftware/ISBoxerEVELauncher#5]
Hello,

EVE supports automated character selection by adding the parameter `/character=`, e.g. `/character=92168909`.

It'd be great if ISBEL would support pre-selecting a character for an account (e.g. by entering a character name and performing an ESI call like this: `https://esi.tech.ccp.is/v1/search/?categories=character&datasource=tranquility&language=en-us&search=CCP%20FoxFour&strict=true`.

**Comment by LaxLacks** [comment]
Implemented in 1.0.0.15
