### ISSUE TITLE
Asks me for master password for every launch, even with previous instance open

### ISSUE THREAD

**Issue by Makeshift** [LavishSoftware/ISBoxerEVELauncher#7]
This suddenly started happening about a month ago. The launcher asks me for my master password every time it opens a new client. I've just updated to 1.0.0.15 to try and fix this to no avail, and have also tried re-adding all my characters and starting from scratch.

I've tried running both the launcher and isboxer with and without admin with no change.

**Comment by Makeshift** [comment]
Oddly seemed to solve itself even after changing nothing as far as I could tell. How weird!

**Comment by JamesDenholm** [comment]
Y'know, I've noticed that admin instances, when minimised to the system tray, cause this issue to crop up.

**Comment by Makeshift** [comment]
That's always been the case for me, and I factor that in when starting my accounts. In this case it wasn't what was causing it.
